server:
  servlet:
    session:
      cookie:
        secure: true
  tomcat:
    protocol-header: x-forwarded-proto

spring:
  application:
    name: pss
  datasource:
    url: jdbc:h2:c:/my/db/pss3
    username: sa
    password: famogo
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /pssdb

---
spring:
  profiles: test
  datasource:

    url: jdbc:h2:~/db/pssTest
---
spring:
  profiles: home
  datasource:
    url: jdbc:h2:~/db/pssHome
